<!DOCTYPE html>
<html>
    <body>
        <h1>Smartass phrase of the day</h1>
        <?php
        require_once __DIR__."/model/GuruPhrases.php";
        $phrases = new GuruPhrases();
        if ($_GET['index']) {
            $phrase = $phrases->get($_GET['index']);
            if (is_null($phrase)) {
                $phrase = "Ops... this one doesn't exist.";
            }
        } else {
            $phrase = $phrases->getRandom();
        }
        ?>
        <p><?= $phrase ?></p>
        <p><a href="guru.php">I want another random one</a></p>
        <p>or</p>
        <form method="get" action="">
            <label for="index">Choose a phrase by number:</label>
            <input name="index" type="text"/>
            <button type="submit">Go!</button>
        </form>
        <p><a href="index.php">Back to home</a></p>
        <p>
            <small>
                All random phrases generated by Dummy Text Generator Plugin for PHPStorm
            </small>
        </p>
    </body>
</html>