<?php
require __DIR__.'/controller/DefaultController.php';
$controller = new DefaultController();
$data = $controller->guruAction();
$phrase = $data['phrase'];
?>
<!DOCTYPE html>
<html>
    <body>
        <h1>Smartass phrase of the day</h1>
        <p><?= $phrase ?></p>
        <p><a href="guru.php">I want another random one</a></p>
        <p>or</p>
        <form method="get" action="">
            <label for="index">Choose a phrase by number:</label>
            <input name="index" type="text"/>
            <button type="submit">Go!</button>
        </form>
        <p><a href="home.php">Back to home</a></p>
        <p>
            <small>
                All random phrases generated by Dummy Text Generator Plugin for PHPStorm
            </small>
        </p>
    </body>
</html>