<!DOCTYPE html>
<html>
    <body>
        <h1>Random Stuff Home</h1>

        <p>Choose your destiny!</p>
        <ul>
            <li><a href="<?= $base_url ?>pirate">I Be Pirate Captein</a></li>
            <li><a href="<?= $base_url ?>guru">Be a Smartass</a></li>
        </ul>
        <p>
            <small>
                All random phrases generated by Dummy Text Generator Plugin for PHPStorm
            </small>
        </p>
    </body>
</html>