<!DOCTYPE html>
<html>
    <body>
        <h1>Yer daily pirate phrases</h1>
        <?php
        $phrases = array(
            "Whine calmly like a big cannon.",
            "Rainy, coal-black planks unlawfully hoist a gutless, big shore.",
            "The jolly roger sings urchin like a rainy jack.",
            "All bilge rats rob undead, coal-black furners.",
            "The cannibal fights with greed, raid the fortress until it falls.",
            "When the anchor screams for port degas, all suns endure proud, stormy lagoons.",
            "Ho-ho-ho! fortune of yellow fever.",
            "Aww, c'mon.",
            "Fine fights lead to the courage.",
            "Cannons wave with endurance at the dead la marsa beach!"
        );
        if ($_GET['index']) {
            $choosen_one = $_GET['index'];
        } else {
            $choosen_one = rand(0, count($phrases) - 1);
        }
        if ($choosen_one < count($phrases)) {
            $phrase = "$choosen_one. $phrases[$choosen_one]";
        } else {
            $phrase = "Ops... this one doesn't exist.";
        }
        ?>
        <p><?= $phrase ?></p>
        <p><a href="">I want another random one</a></p>
        <p>or</p>
        <form method="get" action="">
            <label for="index">Choose a phrase by number:</label>
            <input name="index" type="text"/>
            <button type="submit">Go!</button>
        </form>
        <p><a href="index.php">Back to home</a></p>
        <p>
            <small>
                All random phrases generated by Dummy Text Generator Plugin for PHPStorm
            </small>
        </p>
    </body>
</html>